Update code of `8-subscription` with new version.
probil/howtographql pull request #2
Opened 2018-03-06 10:19 UTC by Youhandan

I have updated `8-subscription` according to `5-authentication` you updated. However I got the error of 'WebSocket connection to '<URL>' failed: WebSocket is closed before the connection is established.' . 

So my page do not update when server data is updated. I can not figure out it but it may not be related to the code I updated.

Please review the code and see if it work well in your local. If you can work, it is not the code problem and could you help me figure out my problem?

2018-03-07 12:30 UTC, probil requested changes
Fix indentation please and I will merge

2018-03-07 12:30 UTC, probil commented on content/frontend/vue-apollo/8-subscriptions.md
> +  		authorization: token ? `Bearer ${token}` : null
too much identation here. And the next line as well

2018-03-07 12:30 UTC, probil commented on content/frontend/vue-apollo/8-subscriptions.md
> +if (!subscriptionData.data.Link) return
Add 2 spaces here (better indentation)

2018-03-07 12:30 UTC, probil commented on content/frontend/vue-apollo/8-subscriptions.md
> +  	if (!subscriptionData.data.Vote) return
Remove spaces at the start so it align with `const` on the next line (indentation)

2018-03-08 01:44 UTC, Youhandan commented
fixed the indention problem.

2018-03-08 10:03 UTC, merged